site_name: NWChem
repo_url: https://github.com/nwchemgit/nwchem-wiki
edit_uri: blob/master/
theme:
  name: readthedocs
  prev_next_buttons_location: both
use_directory_urls: false
plugins:
  - search
  - alternate-link
nav:
      - Documentation Home: Home.md
      - Overview.md
      - System-Description.md
      - Quantum-Mechanical-Methods.md
      - Classical-Methods.md
      - Hybrid-Approaches.md
      - Potential-Energy-Surface-Analysis.md
      - Electronic-Structure-Analysis.md
      - Other-Capabilities.md
      - Examples.md
      - Supplementary-Information.md
      - Compiling-NWChem.md
      - Developer.md
      - Benchmarks.md
      - FAQ.md
      - Known-Bugs.md
