stages:
  - build
  - test

variables:
  USE_MPI: Y
  USE_NOIO: 1
  NWCHEM_MODULES: "nwdft solvation driver vib property mp2_grad ccsd python"
  OMP_NUM_THREADS: 1
  USE_64TO32: Y
  NWCHEM_LONG_PATHS: Y
  GIT_DEPTH: 32

.compile_template: &compile_step
  script:
    - pwd
    - env |grep CI_
    - env|egrep BLAS
    - cd $CI_PROJECT_DIR/src
    - make nwchem_config
    - make 64_to_32
    - make -j3
    - ../contrib/getmem.nwchem 
  except:
    changes:
      - ".travis.yml"
      - "travis/*"

.test_template: &test_step
  variables:
    GIT_CLEAN_FLAGS: -ffdx -e bin -e build -e install
  script:
    - cd $CI_PROJECT_DIR/QA
    - ./doafewqmtests.mpi 2
  except:
    changes:
      - ".travis.yml"
      - "travis/*"

linux64:build_gcc:
  stage: build
  <<: *compile_step
  variables:
    BLAS_LIB: "-lopenblas"
    LAPACK_LIB: "-lopenblas"
    BLAS_SIZE: 4
    SCALAPACK_LIB: "-lscalapack-openmpi  -lopenblas"
    SCALAPACK_SIZE: 4
  tags:
    - ubuntu_bionic

linux64:run_gcc:
  stage: test
  needs: ["linux64:build_gcc"]
  <<: *compile_step
  tags:
    - ubuntu_bionic
