stages:
  - build
  - test

variables:
  USE_MPI: Y
  USE_NOIO: 1
  NWCHEM_MODULES: "nwdft solvation driver vib property mp2_grad ccsd python"
  OMP_NUM_THREADS: 1
  USE_64TO32: Y
  NWCHEM_LONG_PATHS: Y
  GIT_DEPTH: 32

.compile_template: &compile_step
  script:
    - pwd
    - env |grep CI_
    - env|egrep BLAS
    - env|egrep -i mkl
    - env|egrep -i intel
    - cd $CI_PROJECT_DIR/src
    - make nwchem_config
    - make 64_to_32
    - make -j3
    - ../contrib/getmem.nwchem 
  except:
    changes:
      - ".travis.yml"
      - "travis/*"

.test_template: &test_step
  variables:
    GIT_CLEAN_FLAGS: -ffdx -e bin -e build -e install
  script:
    - cd $CI_PROJECT_DIR/QA
    - ./doafewqmtests.mpi 2
  except:
    changes:
      - ".travis.yml"
      - "travis/*"

linux64:build_gcc:
  stage: build
  <<: *compile_step
  variables:
    BLAS_LIB: "-lopenblas"
    LAPACK_LIB: "-lopenblas"
    BLAS_SIZE: 4
    SCALAPACK_LIB: "-lscalapack-openmpi  -lopenblas"
    SCALAPACK_SIZE: 4
  tags:
    - ubuntu_xenial

linux64:build_intel:
  stage: build
  before_script:
    - source /opt/intel/compilers_and_libraries_2018/linux/bin/compilervars.sh  intel64
  <<: *compile_step
  variables:
    FC: ifort
    BLAS_SIZE: 8
    SCALAPACK_SIZE: 8
    BLAS_LIB: "   -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
    LAPACK_LIB: " -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
    SCALAPACK_LIB: " -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl"
  tags:
    - ubuntu_bionic

linux64:run_gcc:
  stage: test
  needs: ["linux64:build_gcc"]
  <<: *test_step
  tags:
    - ubuntu_xenial
