language: c
sudo: required
os: 
  - osx
  - linux
env: 
  - NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
  - NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI-TS MPI_IMPL="mpich"
  - NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI-PR MPI_IMPL="openmpi"
  - NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI-PT MPI_IMPL="mpich"
  - NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI-MT MPI_IMPL="mpich"
  - NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI3   MPI_IMPL="mpich"
  - NWCHEM_MODULES=tce     ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
compiler:
  - gcc
matrix:
  exclude:
    - os: osx
      env: NWCHEM_MODULES=qmandpw ARMCI_NETWORK=MPI-TS MPI_IMPL="mpich"
git:
  depth: 3
before_script:
        - printenv TRAVIS_BUILD_DIR
        - ./travis/build_env.sh
        - gfortran -v
        - mpif90 -show
        - ./travis/config_nwchem.sh
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build_openblas.sh ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build_scalapack.sh ; fi
        - sleep 1
script:
        - ./travis/compile_nwchem.sh
        - ./travis/run_qas.sh


after_failure:
        - tail -20 $TRAVIS_BUILD_DIR/src/tools/build/config.log
        - tail -10 $TRAVIS_BUILD_DIR/src/tools/build/comex/config.log
        - grep -A 2 -B 2 -i error $TRAVIS_BUILD_DIR/src/make.log 
        - head -200 $TRAVIS_BUILD_DIR/src/make.log
        - tail -200 $TRAVIS_BUILD_DIR/src/make.log
        - tail -200 $TRAVIS_BUILD_DIR/src/6log
        - grep -i tce_energy $TRAVIS_BUILD_DIR/src/6log
        - grep d= $TRAVIS_BUILD_DIR/QA/testoutputs/dft_he2+.out
        - grep @ $TRAVIS_BUILD_DIR/QA/testoutputs/h2o_opt.out
        - cat $TRAVIS_BUILD_DIR/QA/testoutputs/dft_he2+.out
        - cat $TRAVIS_BUILD_DIR/QA/testoutputs/prop_mep_gcube.out
              
