language: c
sudo: required
os: 
  - osx
  - linux
env: 
  - NWCHEM_MODULES=qmandpw
  - NWCHEM_MODULES=tce
compiler:
  - gcc
git:
  depth: 3
before_script:
        - printenv TRAVIS_BUILD_DIR
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask uninstall oclint || true  ; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc open-mpi scalapack openblas || true  ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install gfortran gcc python-dev  cmake libopenmpi-dev openmpi-bin tcsh make perl subversion ;fi
        - gfortran -v
        - mpif90 -show
        - ./travis/config_nwchem.sh
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build_openblas.sh ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build_scalapack.sh ; fi
        - sleep 1
script:
        - ./travis/compile_nwchem.sh
        - ./travis/run_qas.sh


after_failure:
        - tail -20 $TRAVIS_BUILD_DIR/src/tools/build/config.log
        - tail -10 $TRAVIS_BUILD_DIR/src/tools/build/comex/config.log
        - grep -A 2 -B 2 -i error $TRAVIS_BUILD_DIR/src/make.log 
        - head -200 $TRAVIS_BUILD_DIR/src/make.log
        - tail -200 $TRAVIS_BUILD_DIR/src/make.log
        - grep d= $TRAVIS_BUILD_DIR/QA/testoutputs/dft_he2+.out
        - grep @ $TRAVIS_BUILD_DIR/QA/testoutputs/h2o_opt.out
              
