language: c
sudo: required
osx_image: xcode10.3
dist: bionic
arch:
  - amd64
  - arm64
os: 
  - osx
  - linux
env: 
  - NWCHEM_MODULES=qmandpw  ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
  - NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
  - NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-TS MPI_IMPL="mpich"
  - NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-PR MPI_IMPL="openmpi"
  - NWCHEM_MODULES="tinyqmpw python" ARMCI_NETWORK=MPI-PT MPI_IMPL="mpich"
  - NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-PT MPI_IMPL="mpich" USE_SIMINT=1 SIMINT_MAXAM=3
  - NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-MT MPI_IMPL="mpich" USE_OPENMP=1
  - NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI3   MPI_IMPL="mpich"
  - NWCHEM_MODULES=tce     ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
  - NWCHEM_MODULES=tce     ARMCI_NETWORK=MPI-PR MPI_IMPL="mpich"
compiler:
  - gcc
matrix:
  exclude:
    - os: osx
      arch: arm64
    - os: osx
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-TS MPI_IMPL="mpich"
    - os: linux
      arch: arm64
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
    - os: linux
      arch: arm64
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-PR MPI_IMPL="openmpi"
    - os: linux
      arch: arm64
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-MT MPI_IMPL="mpich" USE_OPENMP=1
    - os: linux
      arch: arm64
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-PT MPI_IMPL="mpich" USE_SIMINT=1 SIMINT_MAXAM=3
    - os: linux
      arch: arm64
      env: NWCHEM_MODULES=tce     ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
    - os: linux
      arch: arm64
      env: NWCHEM_MODULES=qmandpw  ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
  allow_failures:
    - os: osx
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
    - os: osx
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-PR MPI_IMPL="openmpi"
    - os: osx
      env: NWCHEM_MODULES=tce     ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
    - os: osx
      env: NWCHEM_MODULES=qmandpw  ARMCI_NETWORK=MPI-TS MPI_IMPL="openmpi"
    - os: osx
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI3   MPI_IMPL="mpich"
    - os: osx
      env: NWCHEM_MODULES=tinyqmpw ARMCI_NETWORK=MPI-PT MPI_IMPL="mpich" USE_SIMINT=1 SIMINT_MAXAM=3
    - os: linux
      arch: arm64
git:
  depth: 32
before_script:
        - printenv TRAVIS_BUILD_DIR
        - ./travis/build_env.sh
        - gfortran -v
        - mpif90 -show
        - ./travis/config_nwchem.sh
        - sleep 1
script:
        - ./travis/compile_nwchem.sh
        - grep HAVE_SCA $TRAVIS_BUILD_DIR/src/tools/build/config.h || true
        - ./travis/run_qas.sh


after_failure:
        - ./travis/check_failures.sh
              
