language: c
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
compiler:
  - gcc
env: == default ==
        NWCHEM_TOP=$TRAVIS_BUILD_DIR
        NWCHEM_TARGET=LINUX64
        NWCHEM_MODULES="nwdft driver stepper mp2_grad python"
        USE_MPI=y
        USE_64TO32=y
        BLASOPT="-lopenblas -lpthread -lrt"
        BLAS_SIZE=4
        SCALAPACK="-lopenblas -lpthread -lrt"
        SCALAPACK_SIZE=4
        USE_PYTHONCONFIG=y
        PYTHONVERSION=2.7
        PYTHONHOME=/usr

before_script:
        - sudo apt-get -y install gfortran gcc python-dev libopenblas-dev 
        - sudo apt-get -y install libopenmpi-dev openmpi-bin tcsh make automake libtool autoconf 
        - sudo apt-get -y install perl
        - sudo apt-get -y install libscalapack-openmpi1 libscalapack-mpi-dev
        - cd $NWCHEM_TOP/src && make nwchem_config &&  make 64_to_32 >& 6log &
        - sleep 1
script:
        - cd $NWCHEM_TOP/src && make -j 3 >& make.log
        - tail -100 $NWCHEM_TOP/src/6log
        - tail -100 $NWCHEM_TOP/src/tools/build/config.log
        - tail -200 $NWCHEM_TOP/src/make.log
        - grep SCALAPAC $NWCHEM_TOP/src/tools/build/config.log
after_failure:
        - cat $NWCHEM_TOP/src/6log
        - cat $NWCHEM_TOP/src/tools/build/config.log
        - cat $NWCHEM_TOP/src/tools/build/comex/config.log
        - cat $NWCHEM_TOP/src/make.log

