language: c
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
    - gfortran
    - gcc
    - python-dev
    - libopenblas-dev
    - libopenmpi-dev
    - openmpi-bin
    - tcsh
    - make 
    - automake 
    - libtool 
    - autoconf
    - perl
matrix:
env: == default ==
        NWCHEM_TOP=$TRAVIS_BUILD_DIR
        NWCHEM_TARGET=LINUX64
        NWCHEM_MODULES="nwdft driver stepper mp2_grad"
        USE_MPI=y
        BLASOPT="-lopenblas -lpthread -lrt"
        USE_64TO32=y
        BLAS_SIZE=4

before_script:
        cd $NWCHEM_TOP/src &&
        make nwchem_config && 
        make 64_to_32 >& 6log &
        sleep 1
script:
        - cd $NWCHEM_TOP/src && make -j 3 >& make.log
        - tail -100 $NWCHEM_TOP/src/6log
        - tail -100 $NWCHEM_TOP/src/tools/build/config.log
        - tail -200 $NWCHEM_TOP/src/make.log
after_failure:
        - cat $NWCHEM_TOP/src/6log
        - cat $NWCHEM_TOP/src/tools/build/config.log
        - cat $NWCHEM_TOP/src/make.log

