#$Id: GNUmakefile 25209 2014-02-02 18:41:05Z niri $
# makefile,v 1.8 1994/12/05 20:37:08 og845 Exp

   OBJ = noft_module.o \
	 noft_api.o \
	 ga_unit.o

   LIBRARY = libnoft.a

   USES_BLAS =

 LIB_DEFINES =
     SUBDIRS = 
LIB_INCLUDES = 

HEADERS = 

include ../config/makefile.h
include ../config/makelib.h

